const P=window.NikePatterns,auth=new P.AuthFacade(),$=s=>document.querySelector(s),money=n=>`S/ ${Number(n).toFixed(2)}`;
const view=$("#view"),title=$("#title"),logout=$("#logout"),authDialog=$("#authDialog"),adminLogin=$("#adminLogin"),toast=$("#toast");
const schemas={
 users:{title:"Usuarios",fields:["name","username","role"],labels:["Nombre","Usuario","Rol"]},
 clients:{title:"Clientes",fields:["name","email","phone"],labels:["Nombre","Correo","Teléfono"]},
 suppliers:{title:"Proveedores",fields:["name","contact","channel"],labels:["Nombre","Contacto","Canal"]},
 products:{title:"Productos",fields:["name","category","audience","line","color","size","price","stock","image"],labels:["Nombre","Categoría","Público","Línea","Color","Talla","Precio","Stock","Imagen URL"]}
};
const mediator=new P.MenuMediator();mediator.subscribe(name=>document.querySelectorAll(".admin-side button").forEach(b=>b.classList.toggle("active",b.dataset.view===name)));
function toastMsg(t){toast.textContent=t;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2000)}
function guard(){if(!auth.isAdmin())authDialog.showModal()}guard();
adminLogin.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(!auth.login(f.get("user"),f.get("password")))return toastMsg("Credenciales incorrectas");authDialog.close();render("home")};
logout.onclick=()=>{sessionStorage.removeItem("user");location.href="index.html"};
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>mediator.dispatch(new P.MenuCommand(()=>render(b.dataset.view))));
function render(name){title.textContent=name==="home"?"Dashboard":schemas[name]?.title||name[0].toUpperCase()+name.slice(1);if(schemas[name])renderCrud(name);else if(name==="sales")renderSales();else if(name==="reports")renderReports();else if(name==="patterns")renderPatterns();else renderHome();return name}
function renderHome(){const db=new P.DatabaseSingleton().data,r=new P.ReportFacade().generate();view.innerHTML=`<div class="stats">${[["Productos",db.products.length],["Clientes",db.clients.length],["Proveedores",db.suppliers.length],["Ventas",r.count]].map(x=>`<div class="stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}</div><div class="panel"><h2>Resumen comercial</h2><p>Ventas pagadas acumuladas: <b>${money(r.total)}</b></p><p>Los datos se almacenan en LocalStorage para permitir su funcionamiento estático.</p></div><div class="panel"><h2>Accesos</h2><p>La tienda pública está disponible en <a href="tienda.html">tienda.html</a>. El dashboard y login originales permanecen intactos.</p></div>`}
function renderCrud(entity){const s=schemas[entity],repo=new P.Repository(entity);view.innerHTML=`<div class="panel"><form id="entityForm" class="entity-form">${s.fields.map((f,i)=>`<input name="${f}" placeholder="${s.labels[i]}" ${f==="price"||f==="stock"?'type="number" step="any"':''} required>`).join("")}<button>Agregar</button></form><table class="table"><thead><tr>${s.labels.map(x=>`<th>${x}</th>`).join("")}<th>Acción</th></tr></thead><tbody>${repo.all().map(x=>`<tr>${s.fields.map(f=>`<td>${f==="price"?money(x[f]):x[f]}</td>`).join("")}<td><button onclick="removeEntity('${entity}',${x.id})">Eliminar</button></td></tr>`).join("")}</tbody></table></div>`;entityForm.onsubmit=e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.target));["price","stock"].forEach(k=>{if(data[k])data[k]=+data[k]});if(entity==="users")data=new P.UserFactory().create(data.name,data.username,data.role);if(entity==="products")data=Object.entries(data).reduce((b,[k,v])=>b.set(k,P.ProductFlyweight.shared(v)),new P.ProductBuilder()).build();repo.save(data);toastMsg("Registro creado");renderCrud(entity)}}
function removeEntity(entity,id){new P.Repository(entity).delete(id);renderCrud(entity)}
function renderSales(){const sales=new P.Repository("sales").all();view.innerHTML=`<div class="panel"><table class="table"><thead><tr><th>ID</th><th>Cliente</th><th>Comprobante</th><th>Estado</th><th>Total</th><th>Fecha</th></tr></thead><tbody>${sales.map(s=>`<tr><td>${s.id}</td><td>${s.client}</td><td>${P.ReceiptFactory.create(s.receipt,s)}</td><td>${s.status}</td><td>${money(s.total)}</td><td>${new Date(s.date).toLocaleString()}</td></tr>`).join("")}</tbody></table></div>`}
function renderReports(){const r=new P.ReportFacade(),result=r.generate(new P.StatusExpression("PAGADA"),new P.ScreenVisitor());view.innerHTML=`<div class="stats"><div class="stat"><span>Ventas pagadas</span><b>${result.count}</b></div><div class="stat"><span>Ingresos</span><b>${money(result.total)}</b></div></div><div class="panel"><h2>Reporte de ventas</h2><div class="report-bar" style="width:${Math.min(100,result.count*12)}%"></div><p>Interpreter filtra ventas pagadas, Visitor calcula resultados, Observer permite actualizaciones y Facade unifica la operación.</p><button class="pill" onclick="window.print()">Imprimir / PDF</button></div>`}
function renderPatterns(){view.innerHTML=`<div class="panel"><h2>Patrones por módulo</h2><div class="patterns"><b>Acceso al sistema</b><br>Singleton, Proxy, Facade<br><b>Menú principal</b><br>Mediator, Command, Observer<br><b>Gestión de usuarios</b><br>Repository, Factory Method, Memento<br><b>Gestión de clientes</b><br>Repository, Prototype, Iterator<br><b>Gestión de proveedores</b><br>Repository, Adapter, Bridge<br><b>Gestión de productos</b><br>Repository, Builder, Composite, Decorator, Flyweight<br><b>Ventas</b><br>Abstract Factory, Strategy, Template Method, State, Chain of Responsibility<br><b>Reportes</b><br>Interpreter, Iterator, Visitor, Observer, Facade</div><p>Las implementaciones reutilizables se encuentran en <code>js/patrones.js</code>.</p></div>`}
render("home");
