-- Ejecutar completo en Supabase > SQL Editor.
-- Supabase Auth almacena las credenciales de forma segura en auth.users.

create table if not exists public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text,
  email text unique not null,
  rol text not null default 'CLIENTE' check (rol in ('CLIENTE', 'ADMIN')),
  creado_en timestamptz not null default now()
);

alter table public.usuarios enable row level security;

create or replace function public.es_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.usuarios
    where id = auth.uid() and rol = 'ADMIN'
  );
$$;

drop policy if exists "usuarios pueden ver su perfil" on public.usuarios;
create policy "usuarios pueden ver su perfil"
on public.usuarios for select
using (auth.uid() = id or public.es_admin());

drop policy if exists "usuarios pueden actualizar su perfil" on public.usuarios;
drop policy if exists "administradores actualizan usuarios" on public.usuarios;
create policy "administradores actualizan usuarios"
on public.usuarios for update
using (public.es_admin())
with check (public.es_admin());

create or replace function public.crear_perfil_usuario()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.usuarios (id, nombre, email)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''), new.email);
  return new;
end;
$$;

drop trigger if exists crear_perfil_al_registrarse on auth.users;
create trigger crear_perfil_al_registrarse
after insert on auth.users
for each row execute procedure public.crear_perfil_usuario();

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  categoria text not null,
  publico text not null,
  linea text not null,
  color text,
  talla text,
  precio numeric(10,2) not null check (precio >= 0),
  stock integer not null default 0 check (stock >= 0),
  imagen text,
  creado_en timestamptz not null default now()
);

alter table public.productos enable row level security;
drop policy if exists "catalogo visible para todos" on public.productos;
create policy "catalogo visible para todos"
on public.productos for select
using (true);

create table if not exists public.ventas (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete restrict,
  cliente_email text not null,
  total numeric(10,2) not null check (total >= 0),
  estado text not null default 'PAGADA',
  comprobante text not null default 'BOLETA',
  creado_en timestamptz not null default now()
);

create table if not exists public.venta_items (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references public.ventas(id) on delete cascade,
  producto_id bigint,
  producto_nombre text not null,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(10,2) not null check (precio_unitario >= 0)
);

alter table public.ventas enable row level security;
alter table public.venta_items enable row level security;

drop policy if exists "clientes registran sus ventas" on public.ventas;
create policy "clientes registran sus ventas" on public.ventas for insert
with check (auth.uid() = usuario_id);

drop policy if exists "clientes ven sus ventas" on public.ventas;
create policy "clientes ven sus ventas" on public.ventas for select
using (
  auth.uid() = usuario_id or public.es_admin()
);

drop policy if exists "administradores eliminan ventas" on public.ventas;
create policy "administradores eliminan ventas" on public.ventas for delete
using (public.es_admin());

drop policy if exists "clientes registran detalle de venta" on public.venta_items;
create policy "clientes registran detalle de venta" on public.venta_items for insert
with check (exists (
  select 1 from public.ventas v where v.id = venta_id and v.usuario_id = auth.uid()
));

drop policy if exists "clientes ven detalle de sus ventas" on public.venta_items;
create policy "clientes ven detalle de sus ventas" on public.venta_items for select
using (exists (
  select 1 from public.ventas v
  where v.id = venta_id and (
    v.usuario_id = auth.uid() or public.es_admin()
  )
));

-- Para convertir un usuario existente en administrador:
-- update public.usuarios set rol = 'ADMIN' where email = 'tu-correo@ejemplo.com';
